### ISSUE TITLE
Version solving issue for package_info_plus

### ISSUE THREAD

**Issue by jt274** [martin-braun-net/google_maps_place_picker_mb#73]
**Describe the bug**
Because App depends on google_maps_place_picker_mb ^3.1.2 which depends on package_info_plus ^4.1.0, package_info_plus ^4.1.0 is required.
So, because App depends on package_info_plus ^5.0.0, version solving failed.

**To Reproduce**
1. Create flutter app
2. Add dependencies of `google_maps_place_picker_mb: ^3.1.2` and `package_info_plus: ^5.0.0`
3. Build app

**Expected behavior**
App should build with package being updated to latest dependencies.

**Comment by martin-braun** [comment]
Waiting for https://github.com/zeshuaro/google_api_headers/pull/164 to be shipped.

**Comment by martin-braun** [comment]
@jt274 `package_info_plus` API hasn't changed, it was major bumped due to Kotlin version bump.

Put this in your `pubspec.yaml` until the next update is shipped and you can continue your work:

```yaml
dependency_overrides:
  package_info_plus: any
```

Thank you.

**Comment by jt274** [comment]
@martin-braun This also appears to be an issue with `geolocator 10.1.0`. I had to override both packages to build.

**Comment by zakblacki** [comment]
Also waiting for update

**Comment by martin-braun** [comment]
@zakblacki I want to look into this soon, I will report back.

**Comment by martin-braun** [comment]
@zakblacki `google_api_headers` is still stuck on v4 of `package_info_plus`. I can't really do something about it, unless I choose to maintain even more packages. Flutter's dependency system is annoying.

@jt274 Flutter often succeeds dependency resolution of same packages (dependencies of dependencies), if their major version match, because dependencies are included using `^x.x.x` by default, so only a minimum minor version of the given major version has to match. This obviously breaks if a package maintainer decides to change a major version of a dependency without changing their own major version as well. 

If you update minor dependencies, your build can suddenly stop working, since a major version of a dependency of a dependency doesn't match. This is what the `pubspec.lock` prevents from happening and this is why it should be committed as well. You should consider to install `geolocator 10.0.1` for now. I'm still locked on raising `package_info_plus`.

I start to see why the convention of raising your own major when other dependencies have new majors is such a necessity, so I will consider to incorporate this. This stalling is a huge problem in general, that we cannot overcome without `dependency_overrides`.

**Comment by martin-braun** [comment]
Issue will be solved in the next release
